name: Deploy
run-name: Deploy Library ðŸš€
on:
  push:
    tags:
    - '[0-9]*.[0-9]*.[0-9]*'
jobs:
  deploy_jobs:
    runs-on: macos-latest
    steps:
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set version
      id: version
      run: |
        echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Update version
      run: |
        sed -i -e "s/versionName=[0-9]*.[0-9]*.[0-9]*/versionName=${{ env.tag }}/g" ./media/movie/gradle.properties
        rm -rf ./media/movie/gradle.properties-e
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Update version ${{ env.tag }}"
        git push
    - name: Clean build
      run: ./gradlew media:movie:clean build
    - name: Deploy
      run: |
        ./gradlew media:movie:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
